name: Deploy action for GCP project

on: workflow_dispatch

jobs:
  bootstrap_tfc:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Project ID
        id: get_project
        run: |
          echo "::set-output name=id::$(grep project_id common.hcl | cut -d'=' -f2 | tr -d '"')"

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@0.2.1
        with:
          project_id: ${{ steps.get_project.outputs.id }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: ~1.0.0

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.30.8

      - name: Terragrunt Validate
        #if: github.event_name == 'pull_request' && steps.terragrunt_num_envs.outputs.number <= 1
        if: github.event_name == 'pull_request'
        run: terragrunt run-all validate --terragrunt-exclude-dir ./_init/ --terragrunt-non-interactive
